// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ui.ios
{
	public partial class TimerViewController : UIViewController
	{
		public TimerViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
